# vectors

In [2]:
import numpy as np

In [8]:
# verctor addition
vector1 = np.array([1,2,3,4,5])
vector2 = np.array([9,4,6,2,8])

print("Addition of vectors: \n", vector1 + vector2)
print("Multiplication of vectors: \n", vector1 * vector2)
print("Dot Product: ", np.dot(vector1, vector2))

# angle of vector 
angle = np.arccos(np.dot(vector1, vector2) / ( np.linalg.norm(vector1) * np.linalg.norm(vector2) ))
print("The angle between vectors is : ", angle)


Addition of vectors: 
 [10  6  9  6 13]
Multiplication of vectors: 
 [ 9  8 18  8 40]
Dot Product:  83
The angle between vectors is :  0.6609606073351092


## Vectorize Operations

In [ ]:
# here we want to do vectorize operation jisme ham vector me python core ke sare operation ko use kar sakte hai 
# jisse ham sare elemets pe ek hi baar me opration kar paye
vector1 = np.array(['ujjwal','nirmal','prince','mahesh','suresh'])
print("Normal vector: ",vector1)

vectorize_upper = np.vectorize(str.upper) # yaha pe ham ek method banaye jisse ham numpy ko vectorize kar sake aur uske ander hamne string ko uppercase karne ka method likha 
print("Vector in uppercase: ", vectorize_upper(vector1)) # then hame wohi method me apna vector1 pass kar diya 

# we can make captilize method of that also
vectorize_upper = np.vectorize(str.capitalize)
print("Vector in captilize : ", vectorize_upper(vector1))

Normal vector:  ['ujjwal' 'nirmal' 'prince' 'mahesh' 'suresh']
Vector in uppercase:  ['UJJWAL' 'NIRMAL' 'PRINCE' 'MAHESH' 'SURESH']
Vector in captilize :  ['Ujjwal' 'Nirmal' 'Prince' 'Mahesh' 'Suresh']


In [14]:
# lets do the broadcast jisme ham koi scaler number se operation karte hai vector me 
sales_data = np.array([
[1, 150000, 180000, 220000, 250000], # Paradise Biryani
[2, 120000, 140000, 160000, 190000], # Beijing Bites
[3, 200000, 230000, 260000, 300000], # Pizza Hub
[4, 180000, 210000, 240000, 270000], # Burger Point
[5, 160000, 185000, 205000, 230000] # Chai Point
])

monthly_sales = sales_data[:,1:] / 12 # isse 12 har ek value ke pass jaa ke usko 12 se devide karega
print("Broadcase of vector: \n",monthly_sales)

Broadcase of vector: 
 [[12500.         15000.         18333.33333333 20833.33333333]
 [10000.         11666.66666667 13333.33333333 15833.33333333]
 [16666.66666667 19166.66666667 21666.66666667 25000.        ]
 [15000.         17500.         20000.         22500.        ]
 [13333.33333333 15416.66666667 17083.33333333 19166.66666667]]
