### Array Slicing

In [2]:
import numpy as np

In [3]:
# lets do the basic slicing
arr = np.array([0,1,2,3,4,5,6,7,8,9,10])
sliced = arr[2:5]
print("All elements:", arr[:])
print("Sliced array: ",sliced)

# slicing with steps
print("Step Slicing: ", arr[2:9:3])
print("Negative indexing: ", arr[-8:-1])


All elements: [ 0  1  2  3  4  5  6  7  8  9 10]
Sliced array:  [2 3 4]
Step Slicing:  [2 5 8]
Negative indexing:  [3 4 5 6 7 8 9]


# 2-D array operations

In [6]:
arr_2d = np.array([
    [1,2,3],
    [4,5,6],
    [8,9,0]
])
# now we can point to the specific elemtent of an array by the help of writing row number and position in that row
print("Specific element: ",arr_2d[2,1]) # we are pointing to 2nd row and 1st coloumn in 2nd row

# now we want to refer the whole row of the array
print("Whole row: ", arr_2d[1]) # isse hame whole 1st row ke element ko fetch kar sakte hai

# now we want ki ham fetch kare whole coloumn ko pure array me se 
# we have to write the array name then square brcket me colon and then comma then name of the column
print("Entire coloumn: ",arr_2d[:,2]) # yaha pe ham whole array me se entire 2nd column ko fetch karna chahate hai


Specific element:  9
Whole row:  [4 5 6]
Entire coloumn:  [3 6 0]


# Sorting

In [14]:
unsorted = np.array([9,7,4,6,3,0,1])
print("Sorted array: ",np.sort(unsorted)) # here we pass the our array in the np.sort method

# now lets start the sorting in coloumn wise 
# isme ham top to bottom ham coloum ko sort karte hai 
unsorted_2d_arr = np.array([
    [1,4,6],
    [9,8,6],
    [5,4,3]
])
print("Sorting the 2d array coloumn_wise (top -> bottom): \n", np.sort(unsorted_2d_arr, axis=0)) # axix = 0 for column wise sorting

# now we sort row wise
print("Sorting the 2d array row_wise (left -> right in a row): \n", np.sort(unsorted_2d_arr, axis=1)) # axix = 0 for column wise sorting




Sorted array:  [0 1 3 4 6 7 9]
Sorting the 2d array coloumn_wise (top -> bottom): 
 [[1 4 3]
 [5 4 6]
 [9 8 6]]
Sorting the 2d array row_wise (left -> right in a row): 
 [[1 4 6]
 [6 8 9]
 [3 4 5]]


# Filter


In [15]:
numbers = np.array([1,2,3,4,5,6,7,8,9])

#we can filter the even number and store it in the another array 
# syntax is wierd because we are writing the expression in the square baracket of the previous array

even_num = numbers[numbers % 2 == 0]
print("Even Numbers:", even_num)

Even Numbers: [2 4 6 8]


## Filter with Mask

In [ ]:
mask = numbers > 5
print("The numbers that are greater than 5: ", numbers[mask])

# mask is actually storing the expression and ussi expression ko ham numbers jo ki ek array ham uske ander daal rahe hai jisse ham sirf uss numbers ko hi fetch kar rahe hai numbers array me se jo ki uss mask me stored expression ko fullfill kar rha hai 

The numbers that are greater than 5:  [6 7 8 9]


## Fancy indexing vs np.where()

In [ ]:
num = np.array([1,2,3,4,5,6,7,8,9])

# we can store the index in a lsit type then we can give that list in the array ke index pe so jo jo uss list me number hoga woh -> array ke index se utha ke laayega 

indeces = [1,4,7]
print("Facny indexing: ", num[indeces])

# now we use the where keyword , jisme ham np.where likh ke uske ander ek expression dete hai array ke releted use index se 
where_result = np.where(num > 5) # yaha pe ham actually index ko claculate har rahe hai ki num ke 5 index se bara kon kon sa index aur hai aur yaad rakhna index hamesha 0 se n-1 tak jata hai

print("Where result ke ander kya stored hai: ", where_result)

print("Filtered num array because of where indexing: \n", num[where_result]) # yaha pe ham where_result me stored index of num ko fir se num ke index me daal rahe hai so jo bhi where_result me index stored hai woh num khud me se fetch kar ke layega

## we add 0 in front of num array to easy understanding


Facny indexing:  [1 4 7]
Where result ke ander kya stored hai:  (array([6, 7, 8, 9]),)
Filtered num array because of where indexing: 
 [6 7 8 9]


## Advance where indexing

In [ ]:
# lets take a np array
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
# now we make a condition array where i stored the values from numbers array but with certain condition and expressions
condition_array = np.where(numbers > 5, numbers*4, numbers)
print("Condition array: \n",condition_array)

# yaha pe ham condition array me ham woh values ko stored kar rahe hai jo ki numbers array ke values me se 5 se bare hai toh usko ham 4 se multiply kar dete hai aur ager woh 5 se chote hai toh ham bass numbers array ke values ko uss position ke vlaues ko usi position pe stored karte hai condition array me 

# lets see another example
condition_array_2 = np.where(numbers>3 , "True","False")
print("Condition array 2: \n",condition_array_2)

# aur ha ham yaha number se index ko check karte hai like numbers[0] = 1, numbers[1] = 2, numbers[2] = 3, numbers[3] = 4 so ham yaha dekh sakte hai ki ye bass index 0,1,2 ko hi flase bana rah hai so hamra bass index ke vlaue ko check kar rhae hai 
# so are actually putting condition wala 3 to like numbers[0],numbers[1],numbers[2], and when numbers[3] then we get the condtion flop so we are writing the 3 else wla flase only 

Condition array: 
 [ 1  2  3  4  5 24 28 32 36 40]
Condition array 2: 
 ['False' 'False' 'False' 'True' 'True' 'True' 'True' 'True' 'True' 'True']


# where method is worked like something like if and else statement with conditions
*   if(numbers > 5){
        numbers * 4
    }else{
        numbers
    }

## Adding and Removing the array

In [26]:
# adding 2 arrays
arr1 = np.array([1,2,4,5,6])
arr2 = np.array([3,4,5,6,7])

# if we do like this then we just add the both array elements
add = arr1 + arr2
print("Adding of array: ", add)

# but we want to concatinate the both array in one array
combined = np.concatenate((arr1, arr2)) # we have to pass the both array in tuple
print("Concatination of array: ", combined)



Adding of array:  [ 4  6  9 11 13]
Concatination of array:  [1 2 4 5 6 3 4 5 6 7]


## Compatibility of Array

In [ ]:
# sometimes we have to check the shape of the diffrent array for diffrent purpouse like addition of matrix and multiplication and etc 
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
arr3 = np.array([1,2,3])

print("Compatibility Of Array: ", arr1.shape == arr1.shape) # this gives true if both have same number of row and coloumn and false for diffrences


Compatibility Of Array:  True


## Adding row and coloumns in multi-D array

In [ ]:
# here we want ki ham multidimentional array ko row wise add karte hai
original_array = np.array([
    [1,2,3],
    [4,5,6],
    [5,6,8]
])
new_row = np.array([0,0,0])

with_new_row = np.vstack((original_array,new_row)) # v for vertical matlab ki ham np.vstack mehtod ko use kar ke ham apne array me koi aur array row waise add kar sakte hai 
print("Original array: \n",original_array)
print("Row added to original: \n",with_new_row)

# lets add the array coloumn wise -> with the help of hstack = this if for column wise adding in a matrix

new_col = np.array([
    [1],
    [3],
    [5]
])

with_new_col = np.hstack((original_array,new_col)) # the value is added to each row in coloum wise at last of each row 
print("Coloumn added to original: \n",with_new_col)


Original array: 
 [[1 2 3]
 [4 5 6]
 [5 6 8]]
Row added to original: 
 [[1 2 3]
 [4 5 6]
 [5 6 8]
 [0 0 0]]
Coloumn added to original: 
 [[1 2 3 1]
 [4 5 6 3]
 [5 6 8 5]]


## Delete in an array

In [36]:
arr = np.array([1,2,3,4,5])
deleted_array = np.delete(arr,3) # yaha pe hame parameter me pass karna hai kon se array me se del karna hai aur kiss index ka element delete karna hai
print("After Deletion array is : ", deleted_array)



After Deletion array is :  [1 2 3 5]
