## Learn numPy with basic
Learn about numpy with basic


In [1]:
import numpy as np 

### Creating array from list


In [5]:
arr_1D = np.array([1,2,3,4,5])
print("1D array is: ",arr_1D)

1D array is:  [1 2 3 4 5]


In [8]:
arr_2D = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print("2D array is: ",arr_2D)

2D array is:  [[1 2 3 4 5]
 [1 2 3 4 5]]


### List vs Array in numpy

In [18]:
py_list = [1,2,3,4]
print("List in Pyhton is: ",py_list)

np_array = np.array([1,2,3,4,5,6]) # Element wise multiplication hota hai array me in numpy
print("Multiplication of array: ",np_array * 2)

# lets do test where i want to calculate the time of the array multiplication and the time taken for the list multiplication

import time

start  = time.time()
py_list  = [i*2  for i in range(1000000)]
print("The time taken for the list multplication : ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2 # we can use the same range() in the array of the numpy also by the use of the arange()
print("The time taken for the array multplication : ", time.time() - start)



List in Pyhton is:  [1, 2, 3, 4]
Multiplication of array:  [ 2  4  6  8 10 12]
The time taken for the list multplication :  0.08403515815734863
The time taken for the array multplication :  0.007504463195800781


### the array of the numpy is faster than the list of python

### Creating array from scratch

In [ ]:
# lets make a zeros matrix 
zero  = np.zeros((3, 4))
print("The zero matrix is \n",zero)

# lets make the ones matrix 
ones = np.ones((4,5)) # always remember ki hame ones ek method hai jiske ander hame row and ethe columne ke vlaue pass karna parta hai
print("The ones matrix is \n",ones)

# lets make a matrix for a constant value
full = np.full((3,4),6) # important  = full() ek method hai jiske ander hame denge ki hame kitne row and the column ke matrix banana hai per kis value ka banana hai woh uss barcket ke bahar aa ke comma de ke likhenge 
print("The full matrix is \n",full)

# lets make a matrix of the random values
random = np.random.random((2,3)) # yaha pe hame row aur coluns kitne chaiye uska vlaue likhna hai by usesing the random method ke ander random ko
# and the random.random hamesha ek 0 and 1 ke bich ke koi bhi random vlaue deta hai 
print("The rnadom matrix is \n",random)


# lets use the arange method , jisme ham ek toh starting , end, aur last me kitna step se jump karna hai woh dete hai in the Array
sequence = np.arange(0,10,2)
print("The sequence is: ",sequence) 
# with the help of this method we can print the even number in a sequence 





The zero matrix is 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
The ones matrix is 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
The full matrix is 
 [[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]
The rnadom matrix is 
 [[0.3883804  0.04818226 0.4301807 ]
 [0.23702945 0.65351132 0.22332192]]
The sequence is:  [0 2 4 6 8]


### Vector, Matrix, Tensor

In [ ]:
vector = np.array([1,2,3,4,5])
print("This ia a vector: ",vector)

matrix = np.array([[1,2,3,4],
                   [6,7,8,9]])
print("This is a matrix: \n",matrix)

# tenson is just like an array bass usme hame multiple rows and colums de dete hai jisse hamrae pass bhahut sare dimensions aa jate hai
tensor = np.array([
                    [[1,2,3],[1,2,4]],
                    [[1,2,4],[6,7,8]],
                    [[1,2,3],[8,9,0]]
                    ])
print("This is a tensor: \n", tensor)

This ia a vector:  [1 2 3 4 5]
This is a matrix: 
 [[1 2 3 4]
 [6 7 8 9]]
This is a tensor: 
 [[[1 2 3]
  [1 2 4]]

 [[1 2 4]
  [6 7 8]]

 [[1 2 3]
  [8 9 0]]]


## Array Properties 

In [ ]:
arr = np.array([[1,2,3],
                [5,6,7],
                [0,9,8]])

# we have different kind of properties in the array lets find out most popular one one by one 

print("Shape of array: ", arr.shape) # this return the row and column of the array i.e., shape of the array

print("Dimensions: ",arr.ndim) # ndim is used to show the dimensions of the array // 2 d aarya hai ye 

print("Size: ",arr.size) # this give the total elements in an array

print("Data Type: ",arr.dtype) # iss ham data type of the array pata kar skate


arr_float = np.array([[1,2,3],
                      [1,2,3],
                      [2,3,4.56]])
print("Data Type float: ",arr_float.dtype) # isme ham bass ek hi element ka vlaue float rakhe hai jisse hamra sara arraye ka hi data type float ho gaya hai

arr_char = np.array([[1,2,3],
                      [1,2,3],
                      [2,3,"u"]])
print("Data Type char: ",arr_char.dtype) # isme ham bass ek hi element ka vlaue float rakhe hai jisse hamra sara arraye ka hi data type float ho gaya hai


Shape of array:  (3, 3)
Dimensions:  2
Size:  9
Data Type:  int64
Data Type float:  float64
Data Type char:  <U21


### Array Reshaped concept


In [ ]:
# here we see how we can reshaped a 1 d array to 2d array and then flatten that 2d array toh its normal form 
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
# or we can use the term arange for this operation
arr1 = np.arange(12)
print("Original array is: ",arr1)

# lets reshaped this arr1
reshaped  = arr1.reshape((3,4)) # reshape me hame row kitna chaiye aur coloumn kitna chaiye woh in a bracket pass karna parta hai
print("Reshaped array: \n",reshaped)

# lets flatten that same shaped array 
flattened = reshaped.flatten() # flatten me hame koi argument pass nahi karna parta hai
# ye hame original array ka COPY return karta hai
print("\n flattend array: \n",flattened)

# lets see about the revel
# # jo ki ek view of original array ko return karta hai insted of a copy 
raveled  = reshaped.ravel() # aur ham ye hamersha reshaped array pe lagta hai
print("\n Raveled array: \n", raveled)

# lets see about the transpose of the matrix
transpose = reshaped.T # for transpose of the matrix we use the method T 
print("\n Transpose array: \n", transpose)


Original array is:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 flattend array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### Array Slicing


In [18]:
# lets do the basic slicing
arr = np.array([0,1,2,3,4,5,6,7,8,9,10])
sliced = arr[2:5]
print("All elements:", arr[:])
print("Sliced array: ",sliced)

# slicing with steps
print("Step Slicing: ", arr[2:9:3])
print("Negative indexing: ", arr[-8:-1])


All elements: [ 0  1  2  3  4  5  6  7  8  9 10]
Sliced array:  [2 3 4]
Step Slicing:  [2 5 8]
Negative indexing:  [3 4 5 6 7 8 9]
