# Advance operation with Buisness Examples

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [12]:

# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
[1, 150000, 180000, 220000, 250000], # Paradise Biryani
[2, 120000, 140000, 160000, 190000], # Beijing Bites
[3, 200000, 230000, 260000, 300000], # Pizza Hub
[4, 180000, 210000, 240000, 270000], # Burger Point
[5, 160000, 185000, 205000, 230000] # Chai Point
])
print("=======Zomato Sales Analysis======\n", sales_data)
# lets see how we can fetch the first three row from the array/matrix
# isme main baat jo hame yaad rkahna hai ki jab bhi ham array ke element de toh row and comma and coloum dete hai 
# comma ke start me ham row ko kaisse fetch karne ka logic likhte hai aur comma ke baad ham coloum ko fetch karne ka logic likhte hai
print("First three row from data array: \n",sales_data[0:3]) # because the indexing start from 0 and last term is exclusive 


# now if we want ki ham 1st coloum of ecah row ko hata dete i.e, the indexing of the row then we have to use this method
print("Fresh data without index: \n",sales_data[:,1:]) 
# iss hame [:,] itna likh ke toh hamene sare row ko fetch kar liya aur
# [,1:] itna likh ke 0th term ko hata diya aur 1 se last tak ke sare coloumn ko fetch kar liya

# but for any caluclation starting me sabse pahle ham uska saple nikalte hai
print(np.shape(sales_data))

=======Zomato Sales Analysis======
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]
 [     4 180000 210000 240000 270000]
 [     5 160000 185000 205000 230000]]
First three row from data array: 
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]
Fresh data without index: 
 [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]
(5, 5)


In [ ]:
# lets see how we can add the data coloumn wise 
yearly_total = np.sum(sales_data[:,1:],axis=0) # axis 0 rakhne se ham coloum ke vlaues ko fetch karte hai yaha pe hamsare row ko liye hai fir first coloumn of ech row ko nahi liye hai
print("Yearly total of each resturant: \n     2021    2022    2023  2024 \n ", yearly_total)

# if we want ki ham total reveneu nikale sare resurant ka then,
sum  =0
for i in yearly_total:
    sum  = i  + sum
    print(sum)

Yearly total of each resturant: 
     2021    2022    2023  2024 
  [ 810000  945000 1085000 1240000]
810000
1755000
2840000
4080000


### Minimum sales per resturant

In [32]:
# we want to find the minimum sales per resturant...isme ham har row ka minimum sales nikalenge 
print("Whole data: \n", sales_data,"\n")

min_sales = np.min(sales_data[:,1:], axis=1)
print("The minimum sales per year resturant wise: \n",min_sales)

# now we want ki ham maximum sale per year nihale across the whole resturant
max_sales = np.max(sales_data[:,1:],axis=0)
print("The maximum sales per year: \n",max_sales)

Whole data: 
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]
 [     4 180000 210000 240000 270000]
 [     5 160000 185000 205000 230000]] 

The minimum sales per year resturant wise: 
 [150000 120000 200000 180000 160000]
The maximum sales per year: 
 [200000 230000 260000 300000]


## Average sales per resturant

In [ ]:
# her we find the average sales per resturant // by using MEAN method
average_sales = np.mean(sales_data[:,1:], axis=1)
print("The average sales per resturant is: ",average_sales)

# now we want ki ham cumulative sales nikale har year by year ka
cumulative_Sales = np.cumsum(sales_data[:,1:], axis = 1)
print("Cumulative sales year by year: \n", cumulative_Sales) # isme hota kya hai ki iss saal plus previous saaal ka sales add hoke current saal me likhata hai

The average sales per resturant is:  [200000. 152500. 247500. 225000. 195000.]
Cumulative sales year by year: 
 [[150000 330000 550000 800000]
 [120000 260000 420000 610000]
 [200000 430000 690000 990000]
 [180000 390000 630000 900000]
 [160000 345000 550000 780000]]
